### ISSUE TITLE
Getting exception while running the code

### ISSUE THREAD

**Issue by contact2vikas** [marb2000/DesktopWindow#9]
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at DesktopWindowSample.Program.Main(String[] args) in D:\Temp\DesktopWindow-master\DesktopWindow-master\DesktopWindowSample\DesktopWindowSample\obj\x86\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by marb2000** [comment]
No repro steps. So closing the bug. I also updated to the latest version of the stable WinAppSDK.
